----- git keymaps
vim.keymap.set('n', '<leader>go', ':tab Git<CR>', { desc = 'open git in tab' })
vim.keymap.set('n', '<leader>gr', function()
  local repo = vim.fn.fnamemodify(vim.fn.system('git rev-parse --show-toplevel'):gsub('\n', ''), ':t')
  vim.fn.system('open https://dev.rocketchat.app/refuge/' .. repo)
end, { desc = 'Open repo on [R]efuge' })
vim.keymap.set('n', '<leader>gR', function()
  local root = vim.fn.system('git rev-parse --show-toplevel'):gsub('\n', '')
  local repo = vim.fn.fnamemodify(root, ':t')
  local commit = vim.fn.system('git rev-parse HEAD'):gsub('\n', '')
  local filepath = vim.fn.expand('%:p'):gsub(root .. '/', '')
  local line = vim.fn.line '.'
  local url = ('https://dev.rocketchat.app/refuge/%s/src/commit/%s/%s#L%d'):format(repo, commit, filepath, line)
  local md = ('[%s:%d](%s)'):format(filepath, line, url)
  vim.fn.setreg('+', md)
  vim.fn.system('open ' .. url)
  vim.notify('Copied: ' .. md)
end, { desc = 'Open file+line on [R]efuge' })
vim.keymap.set('n', '<leader>gc', ':Git commit', { desc = 'Make a git commit' })
vim.keymap.set('n', '<leader>gca', ':Git commit --amend', { desc = 'Amend the commit message' })
vim.keymap.set('n', '<leader>ga', ':Git add %<CR>', { desc = 'add current file' })
